=== kcmvp/go-batis/gobatis-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2018 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use this file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (sql* | insert* | update* | delete* | select*)+>
        <!ATTLIST mapper
                namespace CDATA #IMPLIED
                >

        <!ELEMENT select (#PCDATA | include | where | set | foreach | if)*>
        <!ATTLIST select
                id CDATA #REQUIRED
                cacheName CDATA #IMPLIED
                cacheKey CDATA #IMPLIED
                timeout CDATA #IMPLIED
                >

        <!ELEMENT insert (#PCDATA | include | where | set | foreach | if)*>
        <!ATTLIST insert
                id CDATA #REQUIRED
                timeout CDATA #IMPLIED
                >


        <!ELEMENT update (#PCDATA | include | where | set | foreach | if)*>
        <!ATTLIST update
                id CDATA #REQUIRED
                cacheName CDATA #IMPLIED
                cacheKey CDATA #IMPLIED
                timeout CDATA #IMPLIED
                >

        <!ELEMENT delete (#PCDATA | include | where | set | foreach | if)*>
        <!ATTLIST delete
                id CDATA #REQUIRED
                cacheName CDATA #IMPLIED
                cacheKey CDATA #IMPLIED
                timeout CDATA #IMPLIED
                >

        <!-- Dynamic -->

        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >
        <!ELEMENT include (property+)?>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >


        <!ELEMENT sql (#PCDATA | where | set | foreach | if)*>
        <!ATTLIST sql
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                databaseId CDATA #IMPLIED
                >


        <!ELEMENT where (#PCDATA | include | where | set | foreach | if)*>
        <!ELEMENT set (#PCDATA | include | where | set | foreach | if)*>

        <!ELEMENT foreach (#PCDATA | include |where | set | foreach | if)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >


        <!ELEMENT otherwise (#PCDATA | include |where | set | foreach |if)*>

        <!ELEMENT if (#PCDATA | include| where | set | foreach| if)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== kcmvp/go-batis/mapper/dog.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://github.com/kcmvp/go-batis/blob/master/gobatis-mapper.dtd">

<mapper namespace="Dog">

    <insert id="createDog">
        insert into Dog(name,age,price) values (#{name},#{age},#{price})
    </insert>

    <insert id="batchInsert">
        insert into Dog(name,age,price) values
        <foreach collection="dogList" item="dog" index="index" separator=",">
            (#{dog.name},#{dog.age},#{dog.price})
        </foreach>
    </insert>

    <update id="updateDog" cacheKey="#{name}" cacheName="dogcache">
        update Dog
        <set>
            <if test="len(name) > 0">
                name = #{name},
            </if>
            <if test="age > 0">
                age = #{age},
            </if>
            <if test="price > 0">
                price = #{price},
            </if>
            updated_at = CURRENT_TIMESTAMP()
        </set>
        where id = #{id}
    </update>
    <select id="findDogByIdNoCacheName" cacheName="" cacheKey="#{id}">
        select *
        from Dog
        where id = #{id}
    </select>
    <select id="findDogById" cacheName="dogCache" cacheKey="#{id}">
        select *
        from Dog
        where id = #{id}
    </select>


    <select id="searchByExample">
        select count(1)
        from Dog
        <where>
            <if test="len(name) > 0">
                     AND name = #{name}
            </if>
            <if test="age > 0">
                and age = #{age}
            </if>
        </where>
    </select>

    <delete id="deleteDogById" cacheName="dogCache" cacheKey="#{id}">
        delete from dog where levy_serial_number = #{levySerialNumber}
    </delete>

    <!-- batch update begin -->
    <sql id="updateWeekDayPriceCase1">
        UPDATE T_WEEK_DAY_PRICE
        <set>
            <if test="price != null">
                PRICE = ${price},
            </if>
            UPDATED_AT = CURRENT_TIMESTAMP()
        </set>
        where PRICE_PLAN_ID = ${age}
        and NUM_OF_WEEK = ${id}
    </sql>


    <!-- batch update end -->
    <sql id="base">
       name, age, size
    </sql>
    <select id="findMyDog">
        SELECT <include refid="base"/> FROM UUC_COMPANY
        <where>
            <if test="bo.source != null">
                and SOURCE = #{bo.source}
            </if>
            <if test="filterSources != null and filterSources.size >= 0">
                AND SOURCE in (<foreach collection="filterSources" item="item" index="index" separator=",">#{item}</foreach>)
            </if>
            <if test="bo.beginDate!= null">
                <![CDATA[AND UPDATED_AT >= #{bo.beginDate}]]>
            </if>
            <if test="bo.endDate!= null">
                <![CDATA[AND UPDATED_AT <= #{bo.endDate}]]>
            </if>
        </where>
        <if test="size != null and size > 0">
            LIMIT #{offset}, #{size}
        </if>
    </select>

</mapper>
